# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{merb_cucumber}
  s.version = "0.6"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Roman Gonzalez", "David Leal", "Jacques Crocker"]
  s.date = %q{2009-11-10}
  s.description = %q{Cucumber integration for Merb}
  s.email = %q{merbjedi@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.textile"
  ]
  s.files = [
    "CHANGELOG",
     "Generators",
     "LICENSE",
     "README.textile",
     "Rakefile",
     "TODO",
     "lib/generators/cucumber.rb",
     "lib/generators/cucumber/templates/autotest/cucumber_merb_rspec.rb",
     "lib/generators/cucumber/templates/config/cucumber.yml",
     "lib/generators/cucumber/templates/features/authentication/login.feature",
     "lib/generators/cucumber/templates/features/authentication/steps/login_steps.rb",
     "lib/generators/cucumber/templates/features/steps/result_steps.rb",
     "lib/generators/cucumber/templates/features/steps/webrat_steps.rb",
     "lib/generators/cucumber/templates/features/support/env.rb",
     "lib/generators/cucumber/templates/lib/tasks/cucumber.rake",
     "lib/generators/feature.rb",
     "lib/generators/feature/templates/feature.rbt",
     "lib/generators/feature/templates/feature_steps.rb",
     "lib/merb_cucumber.rb",
     "lib/merb_cucumber/helpers/activerecord.rb",
     "lib/merb_cucumber/helpers/datamapper.rb",
     "lib/merb_cucumber/version.rb",
     "lib/merb_cucumber/world/base.rb",
     "lib/merb_cucumber/world/simple.rb",
     "lib/merb_cucumber/world/webrat.rb",
     "spec/cucumber_setup_generator_spec.rb",
     "spec/feature_generator_spec.rb",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/merb/merb_cucumber}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Cucumber integration for Merb}
  s.test_files = [
    "spec/cucumber_setup_generator_spec.rb",
     "spec/feature_generator_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<merb-core>, [">= 1.0.15"])
      s.add_runtime_dependency(%q<cucumber>, [">= 0.4.0"])
      s.add_development_dependency(%q<rspec>, [">= 1.2.9"])
      s.add_development_dependency(%q<merb-gen>, [">= 1.0.15"])
    else
      s.add_dependency(%q<merb-core>, [">= 1.0.15"])
      s.add_dependency(%q<cucumber>, [">= 0.4.0"])
      s.add_dependency(%q<rspec>, [">= 1.2.9"])
      s.add_dependency(%q<merb-gen>, [">= 1.0.15"])
    end
  else
    s.add_dependency(%q<merb-core>, [">= 1.0.15"])
    s.add_dependency(%q<cucumber>, [">= 0.4.0"])
    s.add_dependency(%q<rspec>, [">= 1.2.9"])
    s.add_dependency(%q<merb-gen>, [">= 1.0.15"])
  end
end

